FROM python:3.10

RUN mkdir test_data
COPY test_data test_data/

COPY dist/*.whl .
COPY gunicorn_config.py .

RUN pip install *.whl

CMD ["python", "-m", "gunicorn", "category_api.main:app", "-c", "gunicorn_config.py", "-k", "uvicorn.workers.UvicornWorker"]
