# https://github.com/python-poetry/poetry/discussions/1879
# to improve ^^

## STAGE 1 - Core package(s)

FROM ff_fasttext_build:latest as ff

RUN maturin build

## STAGE 2 - API

FROM python:3.9

RUN mkdir -p /app/ff_fasttext

RUN pip install poetry

COPY test_data/wiki.en.fifu /app/test_data/wiki.en.fifu
COPY test_data/taxonomy.json /app/test_data/taxonomy.json

COPY --from=ff /app/build/target/wheels/*cp39*.whl /app

WORKDIR /app

COPY pyproject.toml /app
COPY poetry.lock /app
# RUN poetry add ./$(ls -1 ./build/wheels/*.whl)

COPY ff_fasttext_api /app/ff_fasttext_api

RUN poetry install

# We want to use poetry for consistency and because it is designed to reproducibly
# manage Python - however the link at the top gives ways of doing this multistage,
# which would be slightly nicer.
CMD ["poetry", "run", "uvicorn", "--factory", "ff_fasttext_api.server:create_app", "--host", "0.0.0.0", "--port", "3003"]