# https://github.com/python-poetry/poetry/discussions/1879
# to improve ^^

## STAGE 1 - Core package(s)

include(`Dockerfile.wheels')

RUN maturin build

## STAGE 2 - API

FROM python:3.9

RUN mkdir -p /app/ff_fasttext

RUN pip install poetry

COPY --from=maturin /app/build/target/wheels/*cp39*.whl /app

WORKDIR /app

COPY api/pyproject.toml /app
COPY api/poetry.lock /app
RUN poetry add $(ls -1 *.whl)

COPY api/ff_fasttext_api /app/ff_fasttext_api

RUN poetry install

# We want to use poetry for consistency and because it is designed to reproducibly
# manage Python - however the link at the top gives ways of doing this multistage,
# which would be slightly nicer.
CMD ["poetry", "run", "uvicorn", "ff_fasttext_api.server:app", "--host", "0.0.0.0", "--port", "80"]
