---

platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task

inputs:
  - name: dp-nlp-category-api

outputs:
  - name: build

caches:
  - path: dp-nlp-category-api/.poetry/
  - path: dp-nlp-category-api/.venv/
  
params:
  USERNAME: default_username
  PASSWORD: default_password

#run:
#  path: sh
#  args:
#    - -exc
#    - |
#      apk add bash
#      apk add make
#      apk add m4
#      docker version
#      docker ps
#      chmod +x dp-nlp-category-api/ci/scripts/build.sh
#      ./dp-nlp-category-api/ci/scripts/build.sh $USERNAME $PASSWORD
