---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.10.6

inputs:
  - name: dp-nlp-category-api

outputs:
  - name: build

run:
  path: dp-nlp-category-api/ci/scripts/build.sh